//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMEmailSetting
    {
        public int SE_HOST_ID { get; set; }
        public string SE_HOST { get; set; }
        public string SE_SMTP_PORT { get; set; }
        public string SE_EMAIL { get; set; }
        public string SE_EMAIL_PASS { get; set; }
        public string SE_SSL { get; set; }
        public string SE_FROM_EMAIL { get; set; }
    }
}
