//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentPriceListHistory
    {
        public long ComponentPriceId { get; set; }
        public long ComponentId { get; set; }
        public long ManufacturerId { get; set; }
        public string ItemPartNo { get; set; }
        public string ComponentPriceDescription { get; set; }
        public Nullable<decimal> ComponentPrice { get; set; }
        public Nullable<decimal> ComponentWeight { get; set; }
        public Nullable<decimal> ComponentLabourTime { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
