//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentSaved
    {
        public long ComponentSavedId { get; set; }
        public long ComponentId { get; set; }
        public long ComponentManufacturerId { get; set; }
        public string ComponentSavedFullName { get; set; }
        public string Size_Description { get; set; }
        public string Size_DescriptionOriginal { get; set; }
        public string Size_DescriptionShort { get; set; }
        public string Size_DescriptionShortOriginal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
