//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersLocationsUserFacility
    {
        public long CustomersLocationsUserFacilityID { get; set; }
        public long LocationContactId { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationID { get; set; }
        public long CustomerFacilityID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
