//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionRequired> ActionRequireds { get; set; }
        public virtual DbSet<CAMEmailSetting> CAMEmailSettings { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentPrice> ComponentPrices { get; set; }
        public virtual DbSet<ComponentPriceList> ComponentPriceLists { get; set; }
        public virtual DbSet<ComponentPriceListDetail> ComponentPriceListDetails { get; set; }
        public virtual DbSet<ComponentPropertyType> ComponentPropertyTypes { get; set; }
        public virtual DbSet<ComponentPropertyValue> ComponentPropertyValues { get; set; }
        public virtual DbSet<ComponentSaved> ComponentSaveds { get; set; }
        public virtual DbSet<ComponentSavedCustomer> ComponentSavedCustomers { get; set; }
        public virtual DbSet<ComponentSavedDetail> ComponentSavedDetails { get; set; }
        public virtual DbSet<ComponentsManufacturer> ComponentsManufacturers { get; set; }
        public virtual DbSet<ComponentsProperty> ComponentsProperties { get; set; }
        public virtual DbSet<ConclusionRecommendation> ConclusionRecommendations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerArea> CustomerAreas { get; set; }
        public virtual DbSet<CustomerLocation> CustomerLocations { get; set; }
        public virtual DbSet<CustomerLocationContact> CustomerLocationContacts { get; set; }
        public virtual DbSet<CustomerLocationHistoryLegacyFile> CustomerLocationHistoryLegacyFiles { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomersLocationsUser> CustomersLocationsUsers { get; set; }
        public virtual DbSet<CustomerUser> CustomerUsers { get; set; }
        public virtual DbSet<Deficiency> Deficiencies { get; set; }
        public virtual DbSet<DeficiencyCategory> DeficiencyCategories { get; set; }
        public virtual DbSet<DeficiencySummary> DeficiencySummaries { get; set; }
        public virtual DbSet<DocumentTitle> DocumentTitles { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FacilitiesArea> FacilitiesAreas { get; set; }
        public virtual DbSet<IdentifyRackingProfile> IdentifyRackingProfiles { get; set; }
        public virtual DbSet<Images_Upload> Images_Upload { get; set; }
        public virtual DbSet<ImpSetting> ImpSettings { get; set; }
        public virtual DbSet<IncidentReport> IncidentReports { get; set; }
        public virtual DbSet<IncidentReportPhoto> IncidentReportPhotoes { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<InspectionDeficiency> InspectionDeficiencies { get; set; }
        public virtual DbSet<InspectionDeficiencyMTO> InspectionDeficiencyMTOes { get; set; }
        public virtual DbSet<InspectionDeficiencyMTODetail> InspectionDeficiencyMTODetails { get; set; }
        public virtual DbSet<InspectionDeficiencyPhoto> InspectionDeficiencyPhotoes { get; set; }
        public virtual DbSet<InspectionDue> InspectionDues { get; set; }
        public virtual DbSet<InspectionFileDrawing> InspectionFileDrawings { get; set; }
        public virtual DbSet<InspectionType> InspectionTypes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ProcessOverview> ProcessOverviews { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationInspectionDeficiency> QuotationInspectionDeficiencies { get; set; }
        public virtual DbSet<QuotationItem> QuotationItems { get; set; }
        public virtual DbSet<QuotationSetting> QuotationSettings { get; set; }
        public virtual DbSet<RACKING_Inspection_Report> RACKING_Inspection_Report { get; set; }
        public virtual DbSet<RackingType> RackingTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ComponentPriceListDetailHistory> ComponentPriceListDetailHistories { get; set; }
        public virtual DbSet<ComponentPriceListHistory> ComponentPriceListHistories { get; set; }
        public virtual DbSet<ComponentSubType_Deleted> ComponentSubType_Deleted { get; set; }
        public virtual DbSet<InspectionStatu> InspectionStatus { get; set; }
    
        public virtual int CloneInspectionData(Nullable<long> sourceInspectionId, Nullable<long> targetInspectionId, Nullable<int> userId)
        {
            var sourceInspectionIdParameter = sourceInspectionId.HasValue ?
                new ObjectParameter("SourceInspectionId", sourceInspectionId) :
                new ObjectParameter("SourceInspectionId", typeof(long));
    
            var targetInspectionIdParameter = targetInspectionId.HasValue ?
                new ObjectParameter("TargetInspectionId", targetInspectionId) :
                new ObjectParameter("TargetInspectionId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloneInspectionData", sourceInspectionIdParameter, targetInspectionIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesBreakdownCategories_Result> Get_DeficienciesBreakdownCategories(Nullable<long> uSERID, Nullable<int> yEAR)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesBreakdownCategories_Result>("Get_DeficienciesBreakdownCategories", uSERIDParameter, yEARParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesBreakdownCategoriesInspection_Result> Get_DeficienciesBreakdownCategoriesInspection(Nullable<long> inspectionId)
        {
            var inspectionIdParameter = inspectionId.HasValue ?
                new ObjectParameter("InspectionId", inspectionId) :
                new ObjectParameter("InspectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesBreakdownCategoriesInspection_Result>("Get_DeficienciesBreakdownCategoriesInspection", inspectionIdParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesBySeverityCustomer_Result> Get_DeficienciesBySeverityCustomer(Nullable<long> uSERID, Nullable<int> yEAR)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesBySeverityCustomer_Result>("Get_DeficienciesBySeverityCustomer", uSERIDParameter, yEARParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesBySeverityCustomerInspection_Result> Get_DeficienciesBySeverityCustomerInspection(Nullable<long> inspectionId)
        {
            var inspectionIdParameter = inspectionId.HasValue ?
                new ObjectParameter("InspectionId", inspectionId) :
                new ObjectParameter("InspectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesBySeverityCustomerInspection_Result>("Get_DeficienciesBySeverityCustomerInspection", inspectionIdParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesBySeverityCustomerNew_Result> Get_DeficienciesBySeverityCustomerNew(Nullable<long> uSERID, Nullable<int> yEAR)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesBySeverityCustomerNew_Result>("Get_DeficienciesBySeverityCustomerNew", uSERIDParameter, yEARParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesTrendFromPreviousYears_Result> Get_DeficienciesTrendFromPreviousYears(Nullable<long> uSERID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesTrendFromPreviousYears_Result>("Get_DeficienciesTrendFromPreviousYears", uSERIDParameter);
        }
    
        public virtual ObjectResult<Get_DeficienciesTrendFromPreviousYearsCustomerLocation_Result> Get_DeficienciesTrendFromPreviousYearsCustomerLocation(Nullable<long> uSERID, Nullable<long> customerLocationId)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DeficienciesTrendFromPreviousYearsCustomerLocation_Result>("Get_DeficienciesTrendFromPreviousYearsCustomerLocation", uSERIDParameter, customerLocationIdParameter);
        }
    
        public virtual ObjectResult<string> GET_InsepctionCode(Nullable<long> customerId, Nullable<long> customerLocationId, string inspectionType)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var inspectionTypeParameter = inspectionType != null ?
                new ObjectParameter("InspectionType", inspectionType) :
                new ObjectParameter("InspectionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GET_InsepctionCode", customerIdParameter, customerLocationIdParameter, inspectionTypeParameter);
        }
    
        public virtual ObjectResult<string> GET_InsepctionCode_bk(Nullable<long> customerId, Nullable<long> customerLocationId, string inspectionType)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var inspectionTypeParameter = inspectionType != null ?
                new ObjectParameter("InspectionType", inspectionType) :
                new ObjectParameter("InspectionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GET_InsepctionCode_bk", customerIdParameter, customerLocationIdParameter, inspectionTypeParameter);
        }
    
        public virtual ObjectResult<GET_InsepctionList_Result> GET_InsepctionList(Nullable<long> customerId, Nullable<long> customerLocationId, string inspectionType)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var inspectionTypeParameter = inspectionType != null ?
                new ObjectParameter("InspectionType", inspectionType) :
                new ObjectParameter("InspectionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_InsepctionList_Result>("GET_InsepctionList", customerIdParameter, customerLocationIdParameter, inspectionTypeParameter);
        }
    
        public virtual ObjectResult<Get_InspectionCountGraph_Result> Get_InspectionCountGraph(Nullable<long> uSERID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_InspectionCountGraph_Result>("Get_InspectionCountGraph", uSERIDParameter);
        }
    
        public virtual ObjectResult<Get_InspectionCountGraph_new_Result> Get_InspectionCountGraph_new(Nullable<long> uSERID, Nullable<int> yEAR)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_InspectionCountGraph_new_Result>("Get_InspectionCountGraph_new", uSERIDParameter, yEARParameter);
        }
    
        public virtual ObjectResult<GetAllInspectionTobeCloned_Result> GetAllInspectionTobeCloned(Nullable<long> inspectionId)
        {
            var inspectionIdParameter = inspectionId.HasValue ?
                new ObjectParameter("InspectionId", inspectionId) :
                new ObjectParameter("InspectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllInspectionTobeCloned_Result>("GetAllInspectionTobeCloned", inspectionIdParameter);
        }
    
        public virtual ObjectResult<GetCustomerDocumentsWithFilters_Result> GetCustomerDocumentsWithFilters(Nullable<long> customerId, Nullable<int> inspectionDocument, Nullable<int> historyDocument, Nullable<int> provinceId, string region, Nullable<int> cityId, Nullable<long> customerLocationId, string documentTypeList)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionDocumentParameter = inspectionDocument.HasValue ?
                new ObjectParameter("InspectionDocument", inspectionDocument) :
                new ObjectParameter("InspectionDocument", typeof(int));
    
            var historyDocumentParameter = historyDocument.HasValue ?
                new ObjectParameter("HistoryDocument", historyDocument) :
                new ObjectParameter("HistoryDocument", typeof(int));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var documentTypeListParameter = documentTypeList != null ?
                new ObjectParameter("DocumentTypeList", documentTypeList) :
                new ObjectParameter("DocumentTypeList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerDocumentsWithFilters_Result>("GetCustomerDocumentsWithFilters", customerIdParameter, inspectionDocumentParameter, historyDocumentParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter, documentTypeListParameter);
        }
    
        public virtual ObjectResult<GetCustomerUsersDocumentsWithFilters_Result> GetCustomerUsersDocumentsWithFilters(Nullable<long> customerId, Nullable<int> inspectionDocument, Nullable<int> historyDocument, Nullable<int> provinceId, string region, Nullable<int> cityId, string customerLocationId, string documentTypeList)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionDocumentParameter = inspectionDocument.HasValue ?
                new ObjectParameter("InspectionDocument", inspectionDocument) :
                new ObjectParameter("InspectionDocument", typeof(int));
    
            var historyDocumentParameter = historyDocument.HasValue ?
                new ObjectParameter("HistoryDocument", historyDocument) :
                new ObjectParameter("HistoryDocument", typeof(int));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId != null ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(string));
    
            var documentTypeListParameter = documentTypeList != null ?
                new ObjectParameter("DocumentTypeList", documentTypeList) :
                new ObjectParameter("DocumentTypeList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerUsersDocumentsWithFilters_Result>("GetCustomerUsersDocumentsWithFilters", customerIdParameter, inspectionDocumentParameter, historyDocumentParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter, documentTypeListParameter);
        }
    
        public virtual ObjectResult<GetInspectionCustomerUserWithFilters_Result> GetInspectionCustomerUserWithFilters(Nullable<long> customerId, string inspectionTypeId, Nullable<int> provinceId, string region, Nullable<int> cityId, string customerLocationId, string inspectionStatusList)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionTypeIdParameter = inspectionTypeId != null ?
                new ObjectParameter("InspectionTypeId", inspectionTypeId) :
                new ObjectParameter("InspectionTypeId", typeof(string));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId != null ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(string));
    
            var inspectionStatusListParameter = inspectionStatusList != null ?
                new ObjectParameter("InspectionStatusList", inspectionStatusList) :
                new ObjectParameter("InspectionStatusList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionCustomerUserWithFilters_Result>("GetInspectionCustomerUserWithFilters", customerIdParameter, inspectionTypeIdParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter, inspectionStatusListParameter);
        }
    
        public virtual ObjectResult<GetInspectionCustomerWithFilters_Result> GetInspectionCustomerWithFilters(Nullable<long> customerId, string inspectionTypeId, Nullable<int> provinceId, string region, Nullable<int> cityId, Nullable<long> customerLocationId, string inspectionStatusList)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionTypeIdParameter = inspectionTypeId != null ?
                new ObjectParameter("InspectionTypeId", inspectionTypeId) :
                new ObjectParameter("InspectionTypeId", typeof(string));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var inspectionStatusListParameter = inspectionStatusList != null ?
                new ObjectParameter("InspectionStatusList", inspectionStatusList) :
                new ObjectParameter("InspectionStatusList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionCustomerWithFilters_Result>("GetInspectionCustomerWithFilters", customerIdParameter, inspectionTypeIdParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter, inspectionStatusListParameter);
        }
    
        public virtual ObjectResult<GetInspectionDetails_Result> GetInspectionDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDetails_Result>("GetInspectionDetails");
        }
    
        public virtual ObjectResult<GetInspectionDetailsByCustomers_Result> GetInspectionDetailsByCustomers(Nullable<long> customerId, Nullable<int> isInspectionFilter)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var isInspectionFilterParameter = isInspectionFilter.HasValue ?
                new ObjectParameter("isInspectionFilter", isInspectionFilter) :
                new ObjectParameter("isInspectionFilter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDetailsByCustomers_Result>("GetInspectionDetailsByCustomers", customerIdParameter, isInspectionFilterParameter);
        }
    
        public virtual ObjectResult<GetInspectionDueCustomerFilters_Result> GetInspectionDueCustomerFilters(Nullable<long> customerId, string inspectionTypeId, Nullable<int> provinceId, string region, Nullable<int> cityId, Nullable<long> customerLocationId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionTypeIdParameter = inspectionTypeId != null ?
                new ObjectParameter("InspectionTypeId", inspectionTypeId) :
                new ObjectParameter("InspectionTypeId", typeof(string));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDueCustomerFilters_Result>("GetInspectionDueCustomerFilters", customerIdParameter, inspectionTypeIdParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter);
        }
    
        public virtual ObjectResult<GetInspectionDueCustomerUserWithFilters_Result> GetInspectionDueCustomerUserWithFilters(Nullable<long> customerId, string inspectionTypeId, Nullable<int> provinceId, string region, Nullable<int> cityId, string customerLocationId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionTypeIdParameter = inspectionTypeId != null ?
                new ObjectParameter("InspectionTypeId", inspectionTypeId) :
                new ObjectParameter("InspectionTypeId", typeof(string));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId != null ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDueCustomerUserWithFilters_Result>("GetInspectionDueCustomerUserWithFilters", customerIdParameter, inspectionTypeIdParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter);
        }
    
        public virtual ObjectResult<GetInspectionDueCustomerWithFilters_Result> GetInspectionDueCustomerWithFilters(Nullable<long> customerId, string inspectionTypeId, Nullable<int> provinceId, string region, Nullable<int> cityId, Nullable<long> customerLocationId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var inspectionTypeIdParameter = inspectionTypeId != null ?
                new ObjectParameter("InspectionTypeId", inspectionTypeId) :
                new ObjectParameter("InspectionTypeId", typeof(string));
    
            var provinceIdParameter = provinceId.HasValue ?
                new ObjectParameter("ProvinceId", provinceId) :
                new ObjectParameter("ProvinceId", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDueCustomerWithFilters_Result>("GetInspectionDueCustomerWithFilters", customerIdParameter, inspectionTypeIdParameter, provinceIdParameter, regionParameter, cityIdParameter, customerLocationIdParameter);
        }
    
        public virtual int SP_DELETE_ComponentPriceList(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ComponentPriceList", iDParameter);
        }
    
        public virtual ObjectResult<SP_Get_AdminDashboardCount_Result> SP_Get_AdminDashboardCount(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_AdminDashboardCount_Result>("SP_Get_AdminDashboardCount", yearParameter);
        }
    
        public virtual ObjectResult<SP_Get_AllEmployeeDashboardCount_Result> SP_Get_AllEmployeeDashboardCount(Nullable<long> uSERID, Nullable<int> yEAR)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_AllEmployeeDashboardCount_Result>("SP_Get_AllEmployeeDashboardCount", uSERIDParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_Get_AllUserDashboardCount_Result> SP_Get_AllUserDashboardCount(Nullable<long> uSERID, Nullable<int> year)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_AllUserDashboardCount_Result>("SP_Get_AllUserDashboardCount", uSERIDParameter, yearParameter);
        }
    
        public virtual ObjectResult<SP_Get_CustomerDashboardCount_Result> SP_Get_CustomerDashboardCount(Nullable<int> year, Nullable<long> customerId)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_CustomerDashboardCount_Result>("SP_Get_CustomerDashboardCount", yearParameter, customerIdParameter);
        }
    
        public virtual ObjectResult<sp_getApprovedInspection_Count_Result> sp_getApprovedInspection_Count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getApprovedInspection_Count_Result>("sp_getApprovedInspection_Count");
        }
    
        public virtual ObjectResult<sp_getApprovedInspection_Count_New_Result> sp_getApprovedInspection_Count_New(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getApprovedInspection_Count_New_Result>("sp_getApprovedInspection_Count_New", yEARParameter);
        }
    
        public virtual ObjectResult<sp_getEmpInspection_Count_Result> sp_getEmpInspection_Count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmpInspection_Count_Result>("sp_getEmpInspection_Count");
        }
    
        public virtual ObjectResult<sp_getEmpInspection_Count_New_Result> sp_getEmpInspection_Count_New(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmpInspection_Count_New_Result>("sp_getEmpInspection_Count_New", yEARParameter);
        }
    
        public virtual ObjectResult<sp_GetIncidentReportsByCustomer_Result> sp_GetIncidentReportsByCustomer(Nullable<long> customerId, Nullable<long> customerLocationId, Nullable<int> provinceID, Nullable<int> cityID, string region)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var customerLocationIdParameter = customerLocationId.HasValue ?
                new ObjectParameter("CustomerLocationId", customerLocationId) :
                new ObjectParameter("CustomerLocationId", typeof(long));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetIncidentReportsByCustomer_Result>("sp_GetIncidentReportsByCustomer", customerIdParameter, customerLocationIdParameter, provinceIDParameter, cityIDParameter, regionParameter);
        }
    
        public virtual ObjectResult<GetInspectionDetailsForMobile_Result> GetInspectionDetailsForMobile(Nullable<long> inspectionId)
        {
            var inspectionIdParameter = inspectionId.HasValue ?
                new ObjectParameter("InspectionId", inspectionId) :
                new ObjectParameter("InspectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDetailsForMobile_Result>("GetInspectionDetailsForMobile", inspectionIdParameter);
        }
    
        public virtual ObjectResult<GetInspectionDetailsForSheet_Result> GetInspectionDetailsForSheet(Nullable<long> inspectionId)
        {
            var inspectionIdParameter = inspectionId.HasValue ?
                new ObjectParameter("InspectionId", inspectionId) :
                new ObjectParameter("InspectionId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInspectionDetailsForSheet_Result>("GetInspectionDetailsForSheet", inspectionIdParameter);
        }
    }
}
