//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public long EmployeeID { get; set; }
        public long UserID { get; set; }
        public string EmployeeEmail { get; set; }

        [Required(ErrorMessage = "Please enter employee name.")]
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Pincode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Gender { get; set; }

        [Required(ErrorMessage = "Please enter title degree.")]
        public string TitleDegrees { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> IsStampingEngineer { get; set; }
		public Nullable<bool> UserStatus { get; set; }
        public string UserToken { get; set; }    }
}
