//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Images_Upload
    {
        public long Id { get; set; }
        public Nullable<long> ImageID { get; set; }
        public string Images { get; set; }
        public Nullable<int> RIR_Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public List<ImgList> imgList { get; set; }
    }

    public class ImgList
    {
        [Key]
        public string filename { get; set; }
    }
}
