//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReport
    {
        public long IncidentReportId { get; set; }
        public string IncidentType { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> CustomerLocationId { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string IncidentNumber { get; set; }
        public string IncidentReportedBy { get; set; }
        public string IncidentArea { get; set; }
        public string IncidentRow { get; set; }
        public string IncidentAisle { get; set; }
        public string IncidentBay { get; set; }
        public string IncidentLevel { get; set; }
        public string IncidentBeamLocation { get; set; }
        public string IncidentFrameSide { get; set; }
        public string IncidentSummary { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
