//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inspection
    {
        public long InspectionId { get; set; }
        public string InspectionDocumentNo { get; set; }
        public string InspectionDocumentNoRef { get; set; }
        public string InspectionType { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime InspectionDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> Reportdate { get; set; }
        public int InspectionStatus { get; set; }
        public Nullable<System.DateTime> InspectionStartedOn { get; set; }
        public Nullable<System.DateTime> InspectionEndOn { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public Nullable<long> CustomerAreaID { get; set; }
        public long EmployeeId { get; set; }
        public string AssignEmployeeIds { get; set; }
        public string FacilitiesAreasIds { get; set; }
        public string ReferenceDocumentIds { get; set; }
        public string CADDocuments { get; set; }
        public string ProcessOverviewIds { get; set; }
        public string ConclusionRecommendationsIds { get; set; }
        public string InspectionPDFPath { get; set; }
        public string CustomerContactIds { get; set; }
        public Nullable<int> RackingTypeId { get; set; }
        public string ActionRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<long> StampingEngineerId { get; set; }
		public List<string> DeletedInspectionDeficiency { get; set; }
    }
}
