//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionDeficiency
    {
        public long InspectionDeficiencyId { get; set; }
        public long InspectionId { get; set; }
        public string CustomerNomenclatureNo { get; set; }
        public string CustomerNomenclatureBayNoID { get; set; }
        public string BayFrameSide { get; set; }
        public string BeamFrameLevel { get; set; }
        public Nullable<int> ConclusionRecommendationsID { get; set; }
        public string ConclusionRecommendationsTitle { get; set; }
        public Nullable<int> DeficiencyID { get; set; }
        public string DeficiencyType { get; set; }
        public string DeficiencyInfo { get; set; }
        public Nullable<bool> Action_ReferReport { get; set; }
        public Nullable<bool> Action_Monitor { get; set; }
        public Nullable<bool> Action_Replace { get; set; }
        public Nullable<bool> Action_Repair { get; set; }
        public Nullable<int> Severity_IndexNo { get; set; }
        public string InspectionDeficiencyTechnicianRemarks { get; set; }
        public Nullable<int> InspectionDeficiencyTechnicianStatus { get; set; }
        public Nullable<int> InspectionDeficiencyAdminStatus { get; set; }
        public Nullable<int> InspectionDeficiencyRequestQuotation { get; set; }
        public Nullable<int> InspectionDeficiencyApprovedQuotation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
