//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionDeficiencyPhoto
    {
        public long InspectionDeficiencyPhotoId { get; set; }
        public long InspectionDeficiencyId { get; set; }
        public string InspectionDeficiencyPhotoPath { get; set; }
        public Nullable<bool> InspectionDeficiencyIsStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
