//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalInspection
    {
        public long InternalInspectionID { get; set; }
        public string InternalInspectionNumber { get; set; }
        public System.DateTime InternalInspectionDate { get; set; }
        public long CustomerID { get; set; }
        public long CustomerLocationID { get; set; }
        public Nullable<long> CustomerFacilityID { get; set; }
        public Nullable<long> CustomerAreaID { get; set; }
        public string ReportedBy { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
