//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalInspectionDeficiency
    {
        public long DeficiencyID { get; set; }
        public long InternalInspectionID { get; set; }
        public long CustomerID { get; set; }
        public string DeficiencyDescription { get; set; }
        public string Severity { get; set; }
        public string RecommendedAction { get; set; }
        public bool IsEngineerReviewRequested { get; set; }
        public Nullable<decimal> EngineerReviewCost { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
