//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalInspectionDeficiency
    {
        public long InternalInspectionDeficiencyID { get; set; }
        public long InternalInspectionID { get; set; }
        public string Area { get; set; }
        public string Row { get; set; }
        public string Aisle { get; set; }
        public string Bay { get; set; }
        public string BeamFrameLevel { get; set; }
        public string BeamLocation { get; set; }
        public string FrameSide { get; set; }
        public string InternalAssessment { get; set; }
        public string InternalAction { get; set; }
        public string RecommendedAction { get; set; }
        public bool IsEngineerReviewRequested { get; set; }
        public Nullable<decimal> EngineerReviewCost { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
