//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAuditLog
    {
        public long InventoryAuditLogId { get; set; }
        public Nullable<long> InventoryFileId { get; set; }
        public long UserId { get; set; }
        public int UserTypeId { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
