//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryColumn
    {
        public long InventoryColumnId { get; set; }
        public long InventoryFileId { get; set; }
        public string ColumnKey { get; set; }
        public string ColumnLabel { get; set; }
        public string ColumnType { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ColumnWidth { get; set; }
        public bool IsLocked { get; set; }
        public bool IsLocationColumn { get; set; }
        public bool IsVisible { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
