//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryFile
    {
        public long InventoryFileId { get; set; }
        public string InventoryDocumentName { get; set; }
        public string StoredFileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSizeBytes { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationID { get; set; }
        public Nullable<long> CustomerFacilityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string Description { get; set; }
        public int RowCount { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
