//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public long QuotationId { get; set; }
        public Nullable<long> InspectionId { get; set; }
        public int QuotationStatus { get; set; }
        public string QuotationNo { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public Nullable<long> CustomerAreaID { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public string YourReference { get; set; }
        public string ValidTo { get; set; }
        public string PaymentTerms { get; set; }
        public string ShipmentMethod { get; set; }
        public Nullable<long> QuotationSalesPersonId { get; set; }
        public string QuotationSalesPersonName { get; set; }
        public Nullable<decimal> LabourUnitPrice { get; set; }
        public Nullable<decimal> QuotationSurcharge { get; set; }
        public Nullable<decimal> QuotationMarkup { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> GSTPer { get; set; }
        public Nullable<decimal> GSTValue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalLabour { get; set; }
        public Nullable<decimal> TotalUnitPrice { get; set; }
        public string QuotationNotes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public List<QuotationItem> objQuotationItems { get; set; }
        public bool updateAll { get; set; }

    }
}
