//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationItem
    {
        public long QuotationInspectionItemId { get; set; }
        public long InspectionId { get; set; }
        public long QuotationId { get; set; }
        public string ItemPartNo { get; set; }
        public string ItemDescription { get; set; }
        public decimal ItemUnitPrice { get; set; }
        public Nullable<decimal> ItemSurcharge { get; set; }
        public Nullable<decimal> ItemMarkup { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal ItemLabour { get; set; }
        public int ItemQuantity { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<decimal> ItemWeightTotal { get; set; }
        public decimal LineTotal { get; set; }
        public decimal ItemLabourTotal { get; set; }
        public Nullable<bool> IsTBD { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
