//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelvingCheckListDetail
    {
        public long ShelvingCheckListDetailId { get; set; }
        public long ShelvingCheckListId { get; set; }
        public int ShelvingCheckListDeficiencyID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Tick_Yes { get; set; }
        public Nullable<bool> Tick_No { get; set; }
        public Nullable<bool> Tick_NA { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
