//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelvingCheckList
    {
        public long ShelvingCheckListId { get; set; }
        public long InspectionId { get; set; }
        public string ShelvingCheckListName { get; set; }
        public string ShelvingCheckListSection { get; set; }
        public Nullable<int> ShelvingCheckListTypeId { get; set; }
        public Nullable<long> ManufacturerId { get; set; }
        public string RowID { get; set; }
        public string Bays { get; set; }
        public string NoOfShelvesPerBay { get; set; }
        public Nullable<decimal> ShelvingCheckListSizeWidthIn { get; set; }
        public Nullable<decimal> ShelvingCheckListSizeDepthIn { get; set; }
        public Nullable<decimal> ShelvingCheckListSizeHeightIn { get; set; }
        public Nullable<decimal> PostWidthIn { get; set; }
        public Nullable<decimal> PostDepthIn { get; set; }
        public Nullable<decimal> PostThicknessIn { get; set; }
        public string PostType { get; set; }
        public Nullable<decimal> ShelfBeamHeightIn { get; set; }
        public Nullable<decimal> ShelfBeamThicknessIn { get; set; }
        public Nullable<int> FrameConnectorQty { get; set; }
        public Nullable<int> TieBarQty { get; set; }
        public Nullable<decimal> CapacityForBay { get; set; }
        public Nullable<decimal> CapacityForShelf { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
