//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRegistrationPerson
    {
        public long TrainingRegistrationPersonID { get; set; }
        public long TrainingRegistrationID { get; set; }
        public long CustomerID { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public long TrainingCourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public decimal CoursePrice { get; set; }
        public string CourseStatus { get; set; }
        public string CertificatePath { get; set; }
        public Nullable<System.DateTime> CertificateExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
